language: clojure
dist: bionic
sudo: true
cache:
  npm: true
  directories:
    - "$HOME/.m2"
addons:
  postgresql: '10'
  ssh_known_hosts: ec2-13-234-119-17.ap-south-1.compute.amazonaws.com
notifications:
  email:
    on_failure: never
    on_success: never
install:
  - lein deps
  - npm install react create-react-class react-dom
before_script:
  - psql -c 'CREATE DATABASE nnts2_test;' -U postgres
script:
  - lein test
before_deploy:
  - openssl aes-256-cbc -K $encrypted_0d868a695e05_key -iv $encrypted_0d868a695e05_iv -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - eval `ssh-agent -s`
  - ssh-add deploy_key
  - lein clean
  - lein with-profile prod uberjar
  - ls $HOME/build/nilenso/nnts2/target
  - scp $HOME/build/nilenso/nnts2/target/nnts2.jar $REMOTE_USER@$REMOTE_TARGET:~/
  - ssh $REMOTE_USER@$REMOTE_TARGET "rm .env && printf 'DB_HOST='$DB_HOST'\nDB_PORT='$DB_PORT'\nDB_PASSWORD='$DB_PASSWORD'\nDB_USERNAME='$DB_USERNAME'\nPORT='$PORT'\nclient_id='$client_id'\nclient_secret='$client_secret >> .env"
deploy:
  provider: script
  skip_cleanup: true
  script: ssh $REMOTE_USER@$REMOTE_TARGET "sudo systemctl restart nnts2.service"
  on:
    branch: master
