language: clojure
dist: bionic
sudo: true
cache:
  npm: true
  directories:
    - "$HOME/.m2"
addons:
  postgresql: '10'
  ssh_known_hosts: ec2-52-66-197-33.ap-south-1.compute.amazonaws.com
notifications:
  email:
    on_failure: never
    on_success: never
install:
  - lein deps
  - npm install react create-react-class react-dom
script:
  - lein test
before_deploy:
  - openssl aes-256-cbc -K $encrypted_0d868a695e05_key -iv $encrypted_0d868a695e05_iv -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - eval `ssh-agent -s`
  - ssh-add deploy_key
  - lein clean
  - lein uberjar
  - ls $HOME/build/nilenso/nnts2/target
  - scp $HOME/build/nilenso/nnts2/target/nnts2.jar $REMOTE_USER@$REMOTE_TARGET:~/
deploy:
  provider: script
  script: sudo systemctl restart nnts2.service
  on:
    branch: master
