language: clojure
dist: bionic
cache:
  npm: true
  directories:
    - "$HOME/.m2"
addons:
  postgresql: '10'
  ssh_known_hosts: "ec2-13-235-113-104.ap-south-1.compute.amazonaws.com"
install:
  - lein deps
  - npm install react create-react-class react-dom
script:
  - lein test
before_deploy:
  - openssl aes-256-cbc -K $encrypted_0d868a695e05_key -iv $encrypted_0d868a695e05_iv -in deploy_rsa.enc -out deploy_rsa -d
  - lein clean
  - lein uberjar
deploy:
  provider: script
  script: scp $HOME/build/nilenso/nnts2/target/nnts2-0.1.0-SNAPSHOT-standalone.jar $REMOTE_USER@$REMOTE_TARGET:~/ 
  on:
    branch: master
