version: "3.7"

services:
  dev_db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: nnts2_dev
      POSTGRES_USER: nnts2
      POSTGRES_PASSWORD:
    ports:
      - "7001:5432"
  test_db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: nnts2_test
      POSTGRES_USER: nnts2
      POSTGRES_PASSWORD:
    ports:
      - "7002:5432"
#  dev_server:
#    build: .
#    environment:
#      CLIENT_ID: ${client_id}
#      CLIENT_SECRET: ${client_secret}
#      REDIRECT_URI: ${redirect_uri}
#    depends_on:
#      - dev_db
#    command: "lein run dev"

